### PR TITLE
Feature/categories tab

### PR DESCRIPTION
**Pull request by AjayVenkatesh2026**
- add a categories tab in bottom tab
- add corresponding screen to it

### CODE REVIEW

**Comment by AjayVenkatesh2026** [comment]
@sunkarivasu please don't merge after reviewing is done.
we need to test it too.

**Review by sunkarivasu — APPROVED** [review]

**Comment by sunkarivasu** [comment]
@AjayVenkatesh2026 : LGTM

**Comment by AjayVenkatesh2026** [comment]
@sunkarivasu can you pull this branch and test it ?

**Comment by sunkarivasu** [comment]
doing the same @AjayVenkatesh2026

**Review by sunkarivasu — APPROVED** [review]

**Review by sunkarivasu — APPROVED** [review]

**Review by sunkarivasu — APPROVED** [review]

**Pull request merged**
